- name: Print variable 
  hosts : localhost
  vars: 
    URL: Print play variable
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: Print Play Variable from vars_file
  hosts : localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Print Play Variable from vars_file
      ansible.builtin.debug:
        msg: URL = {{URL}}
